openshift-cnv/cnv-ci

Makefile
hack/upgrade-cnv.sh

This is a preliminary PR in preparation for the addition of another CI lane to test CNV upgrade.
It adds two "top level" make targets, `make deploy-test` (similar to the existing `make all`) and `make upgrade-test` as a placeholder for the new one.
In parallel, a PR in [openshift/release](https://github.com/openshift/release) will be filed to rename the existing lane's command to `make deploy-test`, as well as to add the new lane.
Once this initial setup is in place and "green", I'll open another PR with the new upgrade test scripts.
Signed-off-by: Zvi Cahana <zvic@il.ibm.com>

Rename make targets in preparation for upgrade lane

---

version-mapping.json

Manually updating [`version-mapping.json`](./version-mapping.json) to have recent builds as baseline.
Picked a recent green build from 4.7 branch, and a recent red one from 4.6 (didn't see anything green).
Signed-off-by: Zvi Cahana <zvic@il.ibm.com>

Update version-mapping.json with recent 4.6/4.7 versions

---

hack/deploy-cnv.sh
hack/patch-hco-pre-test.sh

For 0.34 skip scaling down hco pod, and create configmap.
/cc @zcahana

Align test setup to versions regarding configmap

---

hack/patch-hco-pre-test.sh
hack/upgrade-cnv.sh
hack/wait-for-hco.sh
version-mapping.json

This PR fixes several issues with the tests:
1. Removes the manual `kubevirt-config` ConfigMap creation that was introduced in #22. This is eventually not needed as the ConfigMap is created by HCO.
2. Increase the timeout in waiting for the old CSV to be removed in the upgrade test.
3. Fixes a script syntax problem that caused HCO to be scaled to 0 in 4.6 tests.
/assign @dhiller 
Signed-off-by: Zvi Cahana <zvic@il.ibm.com>

Fix several test issues

---

hack/Dockerfile.upgrade.src.ci
hack/upgrade-cnv.sh
hack/vm.yaml
hack/vmuptime.ext

upgrade with a running VM
- Start a VM before the upgrade and check that it's
still running after the upgrade at VMI level.
- Prepare the infrastructure to check the real uptime at
guest level using expect via virtctl console.
- Bump test versions used on master branch

upgrade with a running VM

---

hack/upgrade-cnv.sh

Check the VM uptime before and after
the upgrade of CNV at guest level
(using expect) to ensure that the
VM didn't get restarted in the upgrade
process.

Checking the VM uptime at guest level

---

hack/Dockerfile.upgrade.src.ci
hack/upgrade-cnv.sh
hack/vm.yaml
hack/vmuptime.ext

- Start a VM before the upgrade and check that it's
still running after the upgrade at VMI level.
- Prepare the infrastructure to check the real uptime at
guest level using expect via virtctl console.

[release-4.8] Upgrade with a running VM

---

hack/Dockerfile.upgrade.src.ci
hack/upgrade-cnv.sh
hack/vm.yaml
hack/vmuptime.ext

- Start a VM before the upgrade and check that it's
still running after the upgrade at VMI level.
- Prepare the infrastructure to check the real uptime at
guest level using expect via virtctl console.

[release-4.7] Upgrade with a running VM

---

hack/Dockerfile.upgrade.src.ci
hack/upgrade-cnv.sh
hack/vm.yaml
hack/vmuptime.ext

- Start a VM before the upgrade and check that it's
still running after the upgrade at VMI level.
- Prepare the infrastructure to check the real uptime at
guest level using expect via virtctl console.

[release-4.9] Upgrade with a running VM

---

hack/upgrade-cnv.sh

Check the VM uptime before and after
the upgrade of CNV at guest level
(using expect) to ensure that the
VM didn't get restarted in the upgrade
process.

[release-4.7] Checking the VM uptime at guest level

---

hack/upgrade-cnv.sh

Check the VM uptime before and after
the upgrade of CNV at guest level
(using expect) to ensure that the
VM didn't get restarted in the upgrade
process.

[release-4.8] Checking the VM uptime at guest level

---

hack/upgrade-cnv.sh

Check the VM uptime before and after
the upgrade of CNV at guest level
(using expect) to ensure that the
VM didn't get restarted in the upgrade
process.

[release-4.9] Checking the VM uptime at guest level

---

hack/test-cnv.sh

The correct name of this environment variable is `ARTIFACT_DIR`, and not `ARTIFACTS_DIR`.
This will also allow seeing the kubevirt test cases results in testgrid, for example:
https://testgrid.k8s.io/redhat-openshift-virtualization#e2e-deploy-4.8
Signed-off-by: orenc1 <ocohen@redhat.com>

Fix ARTIFACT_DIR env var for jUnit

---

hack/Dockerfile.upgrade.src.ci
hack/deploy-cnv.sh
hack/disable-default-catalog-source.sh
hack/upgrade-cnv.sh
manifests/testing/kubevirt-testing-infra.yaml
version-mapping.json

Enhance the deploy and upgrade scripts
so that they can also be used
to deploy and upgrade using only
the production index image.
Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>

Optionally deploy and upgrade from production

---

hack/Dockerfile.upgrade.src.ci
hack/deploy-cnv.sh
hack/disable-default-catalog-source.sh
hack/upgrade-cnv.sh
manifests/testing/kubevirt-testing-infra.yaml
version-mapping.json

Enhance the deploy and upgrade scripts
so that they can also be used
to deploy and upgrade using only
the production index image.
This is a manual cherry-pick of #36
Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>

[release-4.7] Optionally deploy and upgrade from production

---

hack/Dockerfile.upgrade.src.ci
hack/deploy-cnv.sh
hack/disable-default-catalog-source.sh
hack/upgrade-cnv.sh
manifests/testing/kubevirt-testing-infra.yaml
version-mapping.json

Enhance the deploy and upgrade scripts
so that they can also be used
to deploy and upgrade using only
the production index image.
This is a manual cherry-pick of #36
Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>

[release-4.8] Optionally deploy and upgrade from production

---

hack/Dockerfile.upgrade.src.ci
hack/deploy-cnv.sh
hack/disable-default-catalog-source.sh
hack/upgrade-cnv.sh
manifests/testing/kubevirt-testing-infra.yaml
version-mapping.json

Enhance the deploy and upgrade scripts
so that they can also be used
to deploy and upgrade using only
the production index image.
This is a manual cherry-pick of #36
Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>

[release-4.9] Optionally deploy and upgrade from production

---

hack/check-uptime.sh
hack/upgrade-cnv.sh
hack/vmuptime.ext

The test that checks that the VM was not rebooted during CNV upgrade is often stuck and fails the entire job.
This PR is setting a timeout of 60 seconds for the `expect` script, and it is getting retried if the boot time could not be extracted in time.
Signed-off-by: orenc1 <ocohen@redhat.com>

Add retries for VM boot time extraction

---

hack/dump-state.sh
hack/test-cnv.sh
hack/upgrade-cnv.sh
version-mapping.json

- Fix the upgrade logic: if not on production catalog source,
start from the CSV version replaced by
the head of the brew registry and upgrade
to the head of the brew registry
- Fix minor bugs
- Boostrap 4.14
- Amend 4.13 conf pointing to the staging version
- Skip tier1 tests on 4.14 for now, please enable them back once it will be stable enough

Bootstrap 4.14 (skipping tier1 tests)

---

hack/set-imagecontentsourcepolicy.sh

This should allow the code to run if we already have applied the ICSP in a different stage (like in other workflows).
Signed-off-by: Rabin Yasharzadehe <rabin@rabin.io>

Use apply instead of create

---

hack/set-imagecontentsourcepolicy.sh

This should allow the code to run if we already have applied the ICSP in a different stage (like in other workflows).
Signed-off-by: Rabin Yasharzadehe <rabin@rabin.io>

[4.11 Backport] Use apply instead of create

---

hack/set-imagecontentsourcepolicy.sh

This should allow the code to run if we already have applied the ICSP in a different stage (like in other workflows).
Signed-off-by: Rabin Yasharzadehe <rabin@rabin.io>

[4.12 Backport] Use apply instead of create

---

hack/set-imagecontentsourcepolicy.sh

This should allow the code to run if we already have applied the ICSP in a different stage (like in other workflows).
Signed-off-by: Rabin Yasharzadehe <rabin@rabin.io>

[4.13 Backport] Use apply instead of create

---

hack/set-imagecontentsourcepolicy.sh

Sometimes it takes more time, 
```
+ oc wait mcp --all --for condition=updating --timeout=5m
machineconfigpool.machineconfiguration.openshift.io/master condition met
error: timed out waiting for the condition on machineconfigpools/worker
make: *** [set_imagecontentsourcepolicy] Error 1
{"component":"entrypoint","error":"wrapped process failed: exit status 2","file":"k8s.io/test-infra/prow/entrypoint/run.go:84","func":"k8s.io/test-infra/prow/entrypoint.Options.internalRun","level":"error","msg":"Error executing test process","severity":"error","time":"2023-10-23T08:27:24Z"}
error: failed to execute wrapped command: exit status 2
```

Increase mcp wait timeout to 15m

---

manifests/testing/kubevirt-testing-infra.yaml

The latest tag of the disks-images-provider image is 4y old at the time of writing and is not a multi-arch image. Bumping the version of this image to support arm64 testing.
Blocks openshift/release#58544
Refers https://issues.redhat.com/browse/CNV-47087

Bump disks-images-provider to v1.4.0

---

hack/test-cnv.sh

The latest tags in several images used for testing are outdated and not multi-arch. This commit bumps the utility container tag value to v1.4.0.
For example, https://quay.io/repository/kubevirt/fedora-with-test-tooling-container-disk will default to `latest` if this parameter is not set. `latest` was updated 3y ago and is not multi-arch, leading tests on arm64 to fail.
Refers:
- https://github.com/kubevirt/kubevirt/blob/5c05ef0efd76ffbd7286c17086ae1a51602ddcf7/tests/flags/flags.go#L67-L69
- https://github.com/kubevirt/kubevirt/blob/90b00f44a50d2d06bf292b3892d5c49e8a3a22c8/tests/containerdisk/containerdisk.go#L63-L73
Blocks openshift/release#58544

Bump utility container tags

---

hack/test-cnv.sh

After merging https://github.com/openshift/release/pull/60641,
rebuild it to make it use an updated base image of golang-1.22

Rebuild cnv-ci-src 4.16 image

---

hack/dump-state.sh
hack/test-cnv.sh

This is in order to enable storing of kubevirt test suite artifacts during tests run.

Change ARTIFACT_DIR to ARTIFACTS

---

hack/dump-state.sh
hack/test-cnv.sh

This is in order to enable storing of kubevirt test suite artifacts during tests run.

[release-4.18] Change ARTIFACT_DIR to ARTIFACTS

---

Makefile
hack/test-cnv-arm64.sh

This commit adds a test script `test-cnv-arm64.sh` which is a fork of the original `test-cnv.sh` script with ginkgo label filter  set to `(wg-arm64 && !(ACPI,requires-two-schedulable-nodes,cpumodel))`.
Tests selection should be refined to skip less tests in the future but this baseline is a good starting point since all the tests are passing and seem stable.

Create a dedicated script for ARM64 testing

---

hack/Dockerfile.test.src.ci

check if the CI lanes are running and the 4.20 images are present.

[4.20] add `jq` to the test image

---

hack/Dockerfile.test.src.ci
hack/Dockerfile.upgrade.src.ci
hack/test-cnv-arm64.sh
hack/test-cnv.sh
manifests/testing/kubevirt-testing-infra.yaml

* [4.20] Add jq to the test image
Signed-off-by: Oren Cohen <ocohen@redhat.com>
(cherry picked from commit 481e26fe4f5027d330f5b7ba01f9c900888f9d83)
* add jq to upgrade.src.ci image
Signed-off-by: Oren Cohen <ocohen@redhat.com>
(cherry picked from commit 43792c421a490e29819127915bc851f865f0b9cb)
* disks-images-provider: set readOnlyRootFilesystem to false
Signed-off-by: Oren Cohen <ocohen@redhat.com>
(cherry picked from commit 23016a5f3ab8e8d00e7196dd9bea7f10bf287f71)
* Use also beta tags for KUBEVIRT_RELEASE
Signed-off-by: Oren Cohen <ocohen@redhat.com>
(cherry picked from commit faaa4a4202fc8b90ba8d4ed7807f153c95a9a127)
* Remove -oc-path flag from ginkgo execution
This flag no longer exists.
Signed-off-by: Oren Cohen <ocohen@redhat.com>
(cherry picked from commit …

Backport missing changes from release-4.20 branch
